name: Create TaxRelease Branch

on:
  schedule:
    # Schedule: Every Wednesday at 9:00 AM IST (IST is UTC+5:30, so UTC time is 3:30 AM)
    - cron: '30 3 * * 3'

jobs:
  create-branch:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "mnandyala"
          git config --global user.email "nandyala.m.reddy.tpr@vialto.com"

      # Step 3: Create new branch
      - name: Create TaxRelease Branch
        id: create_branch
        run: |
          powershell -Command "
          $BRANCH_NAME = 'TaxRelease-' + (Get-Date -Format yyyy-MM-dd);
          git checkout main;
          git pull origin main;
          git checkout -b $BRANCH_NAME;
          echo ::set-output name=branch_name::$BRANCH_NAME;
          "

      # Step 4: Push the branch to the repository
      - name: Push new branch
        run: |
          git push origin ${{ steps.create_branch.outputs.branch_name }}
