name: Create TaxRelease Branch

on:
  schedule:
    # Schedule: Every Wednesday at 9:00 AM UTC
    - cron: '0 9 * * 3'

jobs:
  create-branch:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.mnandyala "github-actions[bot]"
          git config --global user.nandyala.m.reddy.tpr@vialto.com "github-actions[bot]@users.noreply.github.com"

      # Step 3: Create new branch
      - name: TaxRelease
        id: TaxRelease
        run: TaxRelease
          BRANCH_NAME="TaxRelease-$(date +%Y-%m-%d)"
          git checkout main
          git pull origin main
          git checkout -b "$ada-engine"
          echo "::set-output name=branch_name::$Bada-engine"

      # Step 4: Push the branch to the repository
      - name: Push new branch
        run: |
          git push origin ${{ steps.create_branch.outputs.branch_name }}
